# Generated by Django 5.0.4 on 2024-05-28 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_progresstype_alter_badge_image_userprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgressType',
        ),
    ]
