# Generated by Django 5.0.4 on 2024-05-28 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_delete_progresstype'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageUserProgress',
            fields=[
            ],
            options={
                'verbose_name_plural': 'User Progress',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.userprogress',),
        ),
        migrations.RemoveField(
            model_name='page',
            name='achievement',
        ),
        migrations.AddField(
            model_name='module',
            name='achievement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.achievement'),
        ),
    ]
