# Generated by Django 5.0.4 on 2024-05-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_pageuserprogress_remove_page_achievement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
