# Generated by Django 5.0.4 on 2024-05-20 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userachievement'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='achievement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.achievement'),
        ),
    ]
