# Generated by Django 5.0.4 on 2024-05-28 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_delete_progresstype'),
        ('games', '0003_alter_game_image_delete_userprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUserProgressProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': 'User Progress',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.userprogress',),
        ),
    ]
