# Generated by Django 5.0.4 on 2024-05-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_is_archived_alter_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
